version: '3'
services:
  nuxt:
    container_name: movie-nuxt
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    expose:
      - 3000

  proxy:
    container_name: movie-proxy
    build:
      context: ./proxy
      dockerfile: Dockerfile
    env_file: ./proxy/.env
    volumes:
      - ./proxy:/usr/src/app
      - /usr/src/app/proxy/node_modules
    expose:
      - 3001

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80
    depends_on:
      - nuxt
      - proxy
